site_name: Hands - Agnostic Test Runner
site_description: Reliable agnostic test runner for Robot Framework, pytest, and behave
site_url: https://hands.readthedocs.io

repo_name: 42sol-eu/eden123d
repo_url: https://github.com/42sol-eu/eden123d

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Basic Usage: user-guide/basic-usage.md
    - Test Engines: user-guide/test-engines.md
    - Reports: user-guide/reports.md
  - API Reference: api-reference.md
  - Examples:
    - Pytest: examples/pytest.md
    - Robot Framework: examples/robot.md
    - Behave: examples/behave.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - search.highlight

plugins:
  - search
  - autorefs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
